### ISSUE TITLE
error running main.py

### ISSUE THREAD

**Issue by nazmulislam025** [jxgu1016/Gabor_CNN_PyTorch#10]
I was running your github code for the demo: main.py. But I'm getting the following error:

python main.py --model gcn Traceback (most recent call last):
  File "main.py", line 75, in <module>
    model = get_network_fn(args.model)
  File "/home/nazmul/NAZMUL/Research/Model Inversion Attack/Gabor Filter/GCN/Gabor_CNN_PyTorch/demo/net_factory.py", line 51, in get_network_fn
    'gcn': GCN(channel=4),
  File "/home/nazmul/NAZMUL/Research/Model Inversion Attack/Gabor Filter/GCN/Gabor_CNN_PyTorch/demo/net_factory.py", line 12, in __init__
    GConv(1, 10, 5, padding=2, stride=1, M=channel, nScale=1, bias=False, expand=True),
  File "/home/nazmul/NAZMUL/Research/Model Inversion Attack/Gabor Filter/GCN/Gabor_CNN_PyTorch/gcn/layers/GConv.py", line 83, in __init__
    padding, dilation, groups, bias, expand)
  File "/home/nazmul/NAZMUL/Research/Model Inversion Attack/Gabor Filter/GCN/Gabor_CNN_PyTorch/gcn/layers/GConv.py", line 41, in __init__
    False, _pair(0), groups, bias)
TypeError: __init__() takes exactly 12 arguments (11 given)

Can you please suggest me any solution? Thank you.

**Comment by jxgu1016** [comment]
Thanks for your report. The latest PyTorch (1.1.0) changed some apis and it causes the problem. But all is fixed and please download the latest codes.
